### ISSUE TITLE
Registro Presencial: Problema validación direcciones interesados en intercambio registral (SIR)

### ISSUE THREAD

**Issue by jaruizcarrillo** [Cenatic/alsigm#10]
Hola.

Estamos configurando el módulo de registro presencial (versión 3.0.1) para su integración con SIR. Las pruebas contra SicresTester nos fallan siempre con direcciones de interesados que sean españolas. Todo apunta a que la validación falla por no existir datos en las tablas scr_provexreg y scr_citiesexreg. 
No hemos encontrado ninguna pista en la documentación de cómo se rellenan dichas tablas. No hay tampoco ningún script de carga de las mismas. 
El código de del módulo de integración con el DCO (DIR3) tampoco parece que se ocupe de completarlas.

La duda que tenemos es si esas tablas deben completarse "manualmente" en cada instalación de AlSigm o cuál es el procedimiento para hacerlo.

Un saludo.

**Comment by lfernandezb** [comment]
Buenos días
Nosotros tuvimos el mismo problema. 
Tengo los scripts de carga de datos para la tablas scr_cities, scr_citiesexreg, scr_country, etc.
No veo cómo compartirlos por aquí.
Un saludo

**Comment by lfernandezb** [comment]
Buenas otra vez, 
Tenéis el script de carga completo en SIGM3.0.1/Aplicaciones/BD/PostgreSQL/registro/07-mapeoCiudadesProvinciasDco.sql
Un saludo

**Comment by jaruizcarrillo** [comment]
Muchas gracias !

Nuestra instalación a la versión 3.0.1 se hizo desde una 2.3 utilizando los sucesivos scripts de actualización de BD y en ellos no se incluían los mapeos de ciuidades y provincias (curiosamente sí se incluían los mapeos de paises). Por otra parte, tampoco parece que esos scripts estén en github puesto que no he conseguido encontrarlos mediante la búsqueda.

Utilizaremos los que se distribuyen con los binarios de las aplicaciones. Gracias de nuevo.

Un saludo.

**Comment by lfernandezb** [comment]
Cierto, con las actualizaciones los registros de las tablas de scr_prov no tenían correspondiencia en la de scr_provexreg, etc. Encontré este script por casualidad. Espero que os sirva.
Un saludo

**Comment by jormaral** [comment]
Hola Laura, para compartir código @github tiene una herramienta específica llamada Gist, funciona a modo de pastebin, la tienes en el menú superior.

Saludos.
