### ISSUE TITLE
Error git

### ISSUE THREAD

**Issue by emmsantamaria** [Cenatic/alsigm#7]
Hola Estoy intentando descargarme alsigm desde git  pero me da el siguiente error:

$ git clone https://github.com/Cenatic/alsigm.git
Cloning into 'alsigm'...
fatal: unable to access 'https://github.com/Cenatic/alsigm.git/': Failed to conn
ect to github.com port 443: Timed out

Sabríais decirme que es lo que estoy haciendo mal??

Gracias.

**Comment by jormaral** [comment]
Hola, intenta "telnet github.com 443"
Te debería de salir:Trying 192.30.252.129...
Connected to github.com.
Escape character is '^]'.

Si no, es que puedes tener un cortafuegos y tiene cortado el puerto 443.

**Comment by borillo** [comment]
Buenas @emmsantamaria, recuerda que no es imprescindible clonar el repo con Git.

Puedes bajar el código como ZIP si tienes problemas con el entorno:
https://github.com/Cenatic/alsigm/archive/master.zip

**Comment by emmsantamaria** [comment]
Hola Ricardo,
Si, al final lo hice así, me descargué alsigm-3.0.1.zip, y ya estoy compilando, con mvn clean install -Dmaven.test.skip=true, en el orden indicado. Luego supongo que tendré que seguir configurando el tomcat, bbdd...hasta poderlo tener operativo en mi local.Acepto todo tipo de sugerencia, como con que documentación debo seguir...
Muchas gracias por tu atención, saber que hay alguién hay dispuesto a echarte una mano es de agradecer. Te voy contando.
Eva.





     El Martes 12 de Mayo de 2015 16:03, Ricardo Borillo <notifications@github.com> escribió:
   

 Buenas @emmsantamaria, recuerda que no es imprescindible clonar el repo con Git.Puedes bajar el código como ZIP si tienes problemas con el entorno:
https://github.com/Cenatic/alsigm/archive/master.zip—

**Comment by borillo** [comment]
Me alegro que hayas podido arrancar :)

A día de hoy, la documentación oficial sobre la instalación está en:
https://forja.cenatic.es/plugins/mediawiki/wiki/alsigm/index.php/P%C3%A1gina_principal

Para dudas, lo mejor es usar la lista de correo (soporte-alsigm3.0), ya que ahí están gran parte de los usuarios de SIGM y seguro que alguien te puede ayudar en un momento determinado:
https://forja.cenatic.es/forum/forum.php?forum_id=742

**Comment by emmsantamaria** [comment]
Hola Ricardo,
Estoy intentado Comenzar una nueva conversación, incluso responder a alguna ya creada, pero me dice que no tengo permisos, mi usuario es emmartin.Mi principal duda es que tengo que cambiar en mi código local para que funcione correctamente con la base de datos mia. Te lo comento por si conoces alguna líena en el foro donde se produzca la misma cuentión.
Muchas gracias. Eva.

 


     El Miércoles 13 de Mayo de 2015 9:23, Ricardo Borillo <notifications@github.com> escribió:
   

 Me alegro que hayas podido arrancar :)A día de hoy, la documentación oficial sobre la instalación está en:
https://forja.cenatic.es/plugins/mediawiki/wiki/alsigm/index.php/P%C3%A1gina_principalPara dudas, lo mejor es usar la lista de correo (soporte-alsigm3.0), ya que ahí están gran parte de los usuarios de SIGM y seguro que alguien te puede ayudar en un momento determinado:
https://forja.cenatic.es/forum/forum.php?forum_id=742—

**Comment by borillo** [comment]
Seguro que @jormaral te puede ayudar en ese problema de conexión a la forja.

Ahora mismo no recuerdo ninguna linea del tema en el foro, así que lo mejor sería abrir un hilo nuevo con las dudas que te vayan surgiendo.

**Comment by jormaral** [comment]
Hola Eva, estamos intentando trasladar la comunidad desde la forja de CENATIC a este nuevo espacio, por eso os pedimos que, en la medida de lo posible, utilicéis los canales que existen en Github para todo tipo de consultas. Me ocuparé de decirles a los miembros de la comunidad en la otra forja que se están abriendo aquí consultas.

Gracias por la comprensión.
